[build]
  base    = "VORTREXYN Online Grocery Store"
  publish = "assets"
  command = "npm install"
  functions = "netlify/functions"

[functions]
  included_files = ["views/**"]

[[redirects]]
  from  = "/*"
  to    = "/.netlify/functions/server"
  status = 200
  force  = false
