[build]
  base      = "VORTREXYN Online Grocery Store"
  publish   = "assets"
  command   = "npm install"
  functions = "netlify/functions"

[functions]
  node_bundler   = "nft"
  included_files = ["views/**", "assets/**"]

[[redirects]]
  from   = "/*"
  to     = "/.netlify/functions/server"
  status = 200
  force  = false
