uploads = []
outputs = []

[[generated]]
id = "YxUEUiZY6Ci7wQReA3OBw"
uri = "file://VORTREXYN Online Grocery Store/assets/images/fish-fingers.png"
type = "image"
title = "generated_image"

[[generated]]
id = "GNEaYxGL8ByhrJxXSca06"
uri = "file://VORTREXYN Online Grocery Store/assets/images/hamburger-patties.png"
type = "image"
title = "generated_image"

[[generated]]
id = "6oDyEgyGZHf_xM0gJmjKc"
uri = "file://VORTREXYN Online Grocery Store/assets/images/shelled-prawns.png"
type = "image"
title = "generated_image"

[[generated]]
id = "kumy2ot0WHlF3Bfh0sL4B"
uri = "file://VORTREXYN Online Grocery Store/assets/images/ice-cream.png"
type = "image"
title = "generated_image"

[[generated]]
id = "3ozswf3nanOAUsd9vs_Yb"
uri = "file://VORTREXYN Online Grocery Store/assets/images/panadol.png"
type = "image"
title = "generated_image"

[[generated]]
id = "K5GhQ2X45ytjyKOuyOREK"
uri = "file://VORTREXYN Online Grocery Store/assets/images/bath-soap.png"
type = "image"
title = "generated_image"

[[generated]]
id = "GBlcy8_EpDgSdJPNMbwlC"
uri = "file://VORTREXYN Online Grocery Store/assets/images/garbage-bags.png"
type = "image"
title = "generated_image"

[[generated]]
id = "9TMB8PCBw4Z45-qB_fSSA"
uri = "file://VORTREXYN Online Grocery Store/assets/images/washing-powder.png"
type = "image"
title = "generated_image"

[[generated]]
id = "r-3t1KN5MK8ZDjK672je7"
uri = "file://VORTREXYN Online Grocery Store/assets/images/cheddar-cheese.png"
type = "image"
title = "generated_image"

[[generated]]
id = "b9uDsQWLVi9wpUI6q6AWi"
uri = "file://VORTREXYN Online Grocery Store/assets/images/tbone-steak.png"
type = "image"
title = "generated_image"

[[generated]]
id = "t0ZAu--6l72hOWQSsEli4"
uri = "file://VORTREXYN Online Grocery Store/assets/images/navel-oranges.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ETOYIcduzD_D-uSOGmU36"
uri = "file://VORTREXYN Online Grocery Store/assets/images/bananas.png"
type = "image"
title = "generated_image"

[[generated]]
id = "YOzOKasI3eNu97s5SSP1P"
uri = "file://VORTREXYN Online Grocery Store/assets/images/peaches.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Sq4pTLglstCNYg8SlFTms"
uri = "file://VORTREXYN Online Grocery Store/assets/images/grapes.png"
type = "image"
title = "generated_image"

[[generated]]
id = "08SiSJSqPqQ91dNH8ISZO"
uri = "file://VORTREXYN Online Grocery Store/assets/images/apples.png"
type = "image"
title = "generated_image"

[[generated]]
id = "oCyAuN6LbcR0aZ8RYTPFm"
uri = "file://VORTREXYN Online Grocery Store/assets/images/laundry-bleach.png"
type = "image"
title = "generated_image"

[[generated]]
id = "GpjKNsd-IwSPKrvQBO8mz"
uri = "file://VORTREXYN Online Grocery Store/assets/images/earl-grey-tea.png"
type = "image"
title = "generated_image"

[[generated]]
id = "uHAKrcyjXHt6685aX5XZZ"
uri = "file://VORTREXYN Online Grocery Store/assets/images/instant-coffee.png"
type = "image"
title = "generated_image"

[[generated]]
id = "wJLT6330vlK8OwjScMtG0"
uri = "file://VORTREXYN Online Grocery Store/assets/images/chocolate-bar.png"
type = "image"
title = "generated_image"

[[generated]]
id = "vQ4j_DvMHxKRQRgbRq69w"
uri = "file://VORTREXYN Online Grocery Store/assets/images/dry-dog-food.png"
type = "image"
title = "generated_image"

[[generated]]
id = "6xHW3N22pll7CxOYGd_-t"
uri = "file://VORTREXYN Online Grocery Store/assets/images/bird-food.png"
type = "image"
title = "generated_image"

[[generated]]
id = "-86WYIo0QCHTXdIXXeyN2"
uri = "file://VORTREXYN Online Grocery Store/assets/images/cat-food.png"
type = "image"
title = "generated_image"

[[generated]]
id = "T7mycZA6CSt6euE7WkINr"
uri = "file://VORTREXYN Online Grocery Store/assets/images/fish-food.png"
type = "image"
title = "generated_image"

[[generated]]
id = "DlINpdKOdFTKDRaV8MwoY"
uri = "file://VORTREXYN Online Grocery Store/assets/images/frozen-peas.png"
type = "image"
title = "generated_image"

[[generated]]
id = "xsrY8kDT1SwtNg3_Q-qdl"
uri = "file://VORTREXYN Online Grocery Store/assets/images/frozen-vegetables.png"
type = "image"
title = "generated_image"

[[generated]]
id = "RiOKfn7xFr6fP8Z7E_Fny"
uri = "file://VORTREXYN Online Grocery Store/assets/images/frozen-pizza.png"
type = "image"
title = "generated_image"

[[generated]]
id = "dv_kqCrDkB_Z9R-g7NvfL"
uri = "file://VORTREXYN Online Grocery Store/assets/images/shampoo.png"
type = "image"
title = "generated_image"

[[generated]]
id = "yE3nPeaSaLCk92HbWy7Ub"
uri = "file://VORTREXYN Online Grocery Store/assets/images/toothpaste.png"
type = "image"
title = "generated_image"

[[generated]]
id = "1eoJPMakDQYLlJpPqgm9J"
uri = "file://VORTREXYN Online Grocery Store/assets/images/hand-sanitizer.png"
type = "image"
title = "generated_image"

[[generated]]
id = "rmfUiXsWBEFgRq30cuayD"
uri = "file://VORTREXYN Online Grocery Store/assets/images/dish-soap.png"
type = "image"
title = "generated_image"

[[generated]]
id = "zprCgBuybrpzL7yioaFEB"
uri = "file://VORTREXYN Online Grocery Store/assets/images/paper-towels.png"
type = "image"
title = "generated_image"

[[generated]]
id = "zMz5nZQVJqSFxzZEOkt1w"
uri = "file://VORTREXYN Online Grocery Store/assets/images/toilet-paper.png"
type = "image"
title = "generated_image"

[[generated]]
id = "LBgcRps0SdJey-8r84x3F"
uri = "file://VORTREXYN Online Grocery Store/assets/images/milk.png"
type = "image"
title = "generated_image"

[[generated]]
id = "VVIwObrbBQUWN2BYX5STW"
uri = "file://VORTREXYN Online Grocery Store/assets/images/eggs.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Xdv5pDCso6EwbmvyeWmgU"
uri = "file://VORTREXYN Online Grocery Store/assets/images/apple-juice.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Dfv5bJAVjSRqUMnIT3zHs"
uri = "file://VORTREXYN Online Grocery Store/assets/images/butter.png"
type = "image"
title = "generated_image"

[[generated]]
id = "KJFOz7RxY7LXjGZ1Fng5O"
uri = "file://VORTREXYN Online Grocery Store/assets/images/green-tea.png"
type = "image"
title = "generated_image"

[[generated]]
id = "8Yf24W-u43plDVz5KSZU2"
uri = "file://VORTREXYN Online Grocery Store/assets/images/chicken-breast.png"
type = "image"
title = "generated_image"

[[generated]]
id = "e_93Et1M_b30ioEbR2yUq"
uri = "file://VORTREXYN Online Grocery Store/assets/images/mixed-nuts.png"
type = "image"
title = "generated_image"

[[generated]]
id = "E4pkNjw8BWZ45Q8JhgEKa"
uri = "file://VORTREXYN Online Grocery Store/assets/images/strawberries.png"
type = "image"
title = "generated_image"

[[generated]]
id = "2IUXOn4ndw2elMPoeGJ3B"
uri = "file://VORTREXYN Online Grocery Store/assets/images/crackers.png"
type = "image"
title = "generated_image"

[[generated]]
id = "dNi49aOpHNiCnFoh_HEPb"
uri = "file://VORTREXYN Online Grocery Store/assets/images/mangoes.png"
type = "image"
title = "generated_image"

[[generated]]
id = "NWmIC8Y4Qexnf9vJC6cYN"
uri = "file://VORTREXYN Online Grocery Store/assets/images/lemons.png"
type = "image"
title = "generated_image"

[[generated]]
id = "vmeJFYNVWVssxSh1Hw1Vw"
uri = "file://VORTREXYN Online Grocery Store/assets/images/orange-juice.png"
type = "image"
title = "generated_image"
